name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        az acr build --registry ${{ secrets.AZURE_PREFIX }}acr --image ${{ secrets.AZURE_PREFIX }}containerapp:latest .

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name ${{ secrets.AZURE_PREFIX }}containerapp \
          --resource-group pets-workshop \
          --image ${{ secrets.AZURE_PREFIX }}acr.azurecr.io/${{ secrets.AZURE_PREFIX }}containerapp:latest
