name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Image to ACR
      run: |
        az acr build --registry sammyacr --image sammycontainerapp:latest .

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update --name sammycontainerapp --resource-group pets-workshop --image sammyacr.azurecr.io/sammycontainerapp:latest --environment sammycontainerappenvironment
